/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Notes API
 * Sample backend service
 * OpenAPI spec version: 1.0.0
 */

export type CreateNote201 = {
  id: number;
  message: string;
};
