openapi: 3.0.0
info:
  title: Notes API
  description: Sample backend service
  version: 1.0.0
components:
  schemas: {}
paths:
  /:
    post:
      operationId: createNote
      summary: notes
      tags:
        - Notes
      description: Create a note
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              required:
                - message
              additionalProperties: false
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  message:
                    type: string
                required:
                  - id
                  - message
                additionalProperties: false
servers:
  - url: http://localhost:3333
    description: Development
